import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "../Providers/ReactQueryProvider";
import { ChakraProvider } from "../Providers/ChakraProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <ChakraProvider>
          <body className={inter.className}>{children}</body>
        </ChakraProvider>
      </html>
    </ReactQueryProvider>

  );
}
